name: CI
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test-node:
    name: CI
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
        check-latest: true
        cache-dependency-path: "go.sum"
    - name: cache setup files
      uses: actions/cache@v3
      with:
        path: |
          build
          node_modules
        key: ${{ runner.os }}-${{ hashFiles('Makefile') }}-${{hashFiles('package-lock.json')}}
    - shell: bash
      run: |
        echo '{ "cookie_key_pair": "RmdxSzJhWUxEMmtpV0F3aHdqWStnQ0Yva0E3V0JrSGlDUGZCK3NWNTFKZz0=", "google_api_key":"DUMMY", "google_map_id":"DUMMY"}' > secrets.json
        ./ci.sh

  test-docs:
    name: Docs
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build docs
      run: hugo --source docs --minify