name: CI
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test-node:
    name: CI
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
        check-latest: true
        cache-dependency-path: "go.sum"
    - name: cache setup files
      uses: actions/cache@v3
      with:
        path: |
          build
          node_modules
        key: ${{ runner.os }}-${{ hashFiles('Makefile') }}-${{hashFiles('package-lock.json')}}
    - shell: bash
      run: |
        echo '{ "google_analytics_tracking_id":"DUMMY", "google_api_key":"DUMMY", "google_map_id":"DUMMY"}' > keys.json
        ./ci.sh
